#ifndef CONFIGURATION_RTEMS_CIM_HH
#define CONFIGURATION_RTEMS_CIM_HH

#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_TIMER_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_NULL_DRIVER

//#define CONFIGURE_MAXIMUM_SEMAPHORES     20
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES 20
#define CONFIGURE_MAXIMUM_TASKS          20
#define CONFIGURE_MAXIMUM_USER_EXTENSIONS 1
#define CONFIGURE_MAXIMUM_DRIVERS 10

#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 50
#define CONFIGURE_MICROSECONDS_PER_TICK 10000

#define CONFIGURE_EXECUTIVE_RAM_SIZE   (2048*1024)

// for telnetd and shell and IMFS
#define RTEMS_NETWORKING
#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 50
#define CONFIGURE_APPLICATION_NEEDS_LIBBLOCK
#define CONFIGURE_MAXIMUM_PTYS 4

#define CONFIGURE_SHELL_COMMANDS_INIT
#define CONFIGURE_SHELL_COMMANDS_ALL
#define CONFIGURE_SHELL_MOUNT_TFTP
#define CONFIGURE_SHELL_MOUNT_FTP
#define CONFIGURE_SHELL_MOUNT_NFS

#include <rtems/shellconfig.h>

#define CONFIGURE_USE_IMFS_AS_BASE_FILESYSTEM
#define CONFIGURE_IMFS_MEMFILE_BYTES_PER_BLOCK  256

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE
#define CONFIGURE_INIT

#include <rtems.h>

extern "C" rtems_task Init(rtems_task_argument);

#include <rtems/confdefs.h>

#endif
