// -*-Mode: C;-*-
/**
@file
@brief The lookup tables used by mem_get{Phys|Flags|PhysFlags}{Read|Write}() for ARM Cortex A9 (ARM v7).

@verbatim
                               Copyright 2013
                                    by
                       The Board of Trustees of the
                    Leland Stanford Junior University.
                           All rights reserved.
@endverbatim

@par Facility:
DAT

@author
Steve Tether <tether@slac.stanford.edu>

@par Date created:
2013/10/11

@par Last commit:
\$Date: 2014-04-07 21:30:01 -0700 (Mon, 07 Apr 2014) $ by \$Author: panetta $.

@par Revision number:
\$Revision: 3125 $

@par Location in repository:
\$HeadURL: file:///afs/slac.stanford.edu/g/cci/repositories/ctkrepo/core_tags/prod/V2.4.2/tool/memory/src/armCA9/memFlagsTable.c $

@par Credits:
SLAC
*/


#include "memory/mem.h"

/** A byte offset into a table is calculated by masking the value
    of the Physical Address Register by 0xfc after a successful
    ATS1CPR or ATS1CPW operation.
*/

/* The table to use after ATS1CPR. MEM_READ will always be
   set. MEM_CACHED will be set if either inner or outer caching is
   indicated.
*/
int mem_flagsLookupRead[] = {
  MEM_READ,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_DEVICE | MEM_HANDSHAKE,
  MEM_READ | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_DEVICE,
  MEM_READ | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_DEVICE | MEM_CACHED,
  MEM_READ,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_CACHED,
  MEM_READ | MEM_SHARED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_SHARED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_SHARED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_SHARED | MEM_CACHED
};

/* The table to use after ATS1CPW operation. The same
   as the first table except that MEM_WRITE is also always set.
*/
int mem_flagsLookupWrite[] = {
  MEM_READ | MEM_WRITE,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_HANDSHAKE,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_HANDSHAKE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_DEVICE | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED,
  MEM_READ | MEM_WRITE | MEM_SHARED | MEM_CACHED
};
