
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpci.h"

/*
* The configuration table for devices
*/

XPci_Config XPci_ConfigTable[] =
{
	{
		XPAR_PCI32_BRIDGE_DEVICE_ID,
		XPAR_PCI32_BRIDGE_BASEADDR,
		XPAR_PCI32_BRIDGE_DMA_BASEADDR,
		XPAR_PCI32_BRIDGE_PCIBAR_0,
		XPAR_PCI32_BRIDGE_PCIBAR_1,
		XPAR_PCI32_BRIDGE_PCIBAR_2,
		XPAR_PCI32_BRIDGE_PCI_PREFETCH_0,
		XPAR_PCI32_BRIDGE_PCI_PREFETCH_1,
		XPAR_PCI32_BRIDGE_PCI_PREFETCH_2,
		XPAR_PCI32_BRIDGE_PCI_SPACETYPE_0,
		XPAR_PCI32_BRIDGE_PCI_SPACETYPE_1,
		XPAR_PCI32_BRIDGE_PCI_SPACETYPE_2,
		XPAR_PCI32_BRIDGE_DMA_CHAN_TYPE,
		XPAR_PCI32_BRIDGE_BRIDGE_IDSEL_ADDR_BIT
	}
};


